[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run build",
  "npx esbuild server/production.ts --platform=node --packages=external --bundle --format=esm --outfile=dist/production.js"
]

[start]
cmd = "node dist/production.js"