[phases.build]
cmds = [
  "npm ci",
  "npx vite build",
  "npx esbuild server/production.ts --platform=node --packages=external --bundle --format=esm --outfile=dist/production.js"
]

[start]
cmd = "node dist/production.js"

[variables]
NODE_ENV = "production"